const path = {
  // ===== PUBLIC =====
  PUBLIC: "/",
  HOME: "home",
  LOGIN: "login",
  MY_ACCOUNT: "my-account",
  PROFILE: "profile",
  ORDERS: "orders",
  WISHLIST: "wishlist",
  PRODUCTS: "product",
  PRODUCT_CATEGORY: "product/:category",
  BLOGS: "blogs",
  OUR_SERVICES: "our-services",
  REGISTER: "register",
  FINAL_REGISTER: "finalRegister/:status",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password/:token",
  CART: "cart",
  CHECKOUT: "checkout",
  DETAIL_PRODUCT__ID__SLUG: "detail-product/:pid/:slug",
  DETAIL_PRODUCT: "detail-product",
  NOT_FOUND: "*",
  VERIFY_EMAIL: "finalRegister/:token",
  VERIFY_PENDING: "verify-pending",
  CART_SIDEBAR: "",
  DETAIL_BLOG__ID: "blog/:id",
  CONTACT_US: "contact-us",

  // ===== ADMIN =====
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_USERS_CREATE: "/admin/users/create",
  ADMIN_USERS_EDIT__ID: "/admin/users/edit/:id",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_PRODUCTS_CREATE: "/admin/products/create",
  ADMIN_PRODUCTS_EDIT__ID: "/admin/products/edit/:id",
  ADMIN_PRODUCTS_LIST: "/admin/products/list",
};

export default path;
